---
title: "edna_db"
author: "Jake Eisaguirre"
date: "2022-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, here, janitor, lubridate, RPostgres, rstudioapi, DBI, parsedate, stringr, hms,
                 anytime, terra, sp, rgdal, RWmisc, proj4)
```

# serdp edna data

# full serdp edna data

```{r}

full_serdp_edna <- read_csv(here("data", "serdp", "edna", "serdp_edna.csv")) %>% 
  clean_names()

```


## serdp edan site table
```{r}

serdp_site_edna <- full_serdp_edna %>%
  select(c(state, site_number, date_collected)) %>% 
  unite(site_code, state:site_number,  sep = "", na.rm = T, remove = F) %>% 
  mutate(site_code = str_to_lower(site_code),
         date_collected = format_iso_8601(parse_date(date_collected))) %>% 
  mutate(region = case_when(state == "PA" ~ "pennsylvania",
                           state == "NM" ~ "new_mexico",
                           state == "LA" ~ "louisiana",
                           state == "TN" ~ "tennessee",
                           state == "VT" ~ "vermont")) %>% 
  select(!c(state, site_number)) %>% 
  group_by(site_code, date_collected) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(!duplicated(temp_id)) %>% 
  select(!c(temp_id))

codes_to_names <- read_csv(here("data", "serdp", "edna", "join_site.csv")) %>% 
  mutate(site = str_replace_all(site, " ", "_"),
         site = str_replace(site, " ", "-"))


serdp_edna_visit <- left_join(serdp_site_edna, codes_to_names, by = c("site_code")) 

serdp_edna_sitetable <- serdp_edna_visit %>% ungroup() %>% 
  select(!c(date_collected)) %>% 
  group_by(site_code) %>% 
  filter(!duplicated(site_code))
  
  

```


## serdp_edna_date_table
```{r}

serdp_edna_visit_table <- serdp_edna_visit %>% 
  mutate(year = year(date_collected),
         month = month(date_collected),
         day = day(date_collected)) %>% 
  select(!c(region, site))
  

```


## serdp_edna_collection
```{r}

collection_serdp_edna <- full_serdp_edna %>%
  clean_names() %>% 
  unite(site_code, state:site_number,  sep = "", na.rm = T, remove = F) %>% 
  mutate(site_code = str_to_lower(site_code),
         date_collected = format_iso_8601(parse_date(date_collected)),
         ext_date = format_iso_8601(parse_date(ext_date)),
         date_ran = format_iso_8601(parse_date(date_ran))) %>% 
  mutate(region = case_when(state == "PA" ~ "pennsylvania",
                           state == "NM" ~ "new_mexico",
                           state == "LA" ~ "louisiana",
                           state == "TN" ~ "tennessee",
                           state == "VT" ~ "vermont"),
         control = case_when(control_experimental == "C" ~ 1,
                             control_experimental == "E" ~ 0)) %>% 
  select(!c(state, site_number)) %>% 
  group_by(site_code, date_collected) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(!duplicated(temp_id)) %>% 
  select(!c(temp_id, year, month, control_experimental)) %>% 
  relocate(control, .after = number_filters) %>% 
  mutate(sample_pass_fail = case_when(sample_pass_fail == "P" ~ 1,
                                      sample_pass_fail == "F, neg ext control had Bd" ~ 0),
         bd_pos_neg = case_when(bd_pos_neg == "N" ~ 0,
                                bd_pos_neg == "P" ~ 1),
         bsal_pos_neg = case_when(bsal_pos_neg == "N" ~ 0,
                                  bsal_pos_neg == "N;N;N" ~ 0),
         q_pcr_neg_control = case_when(q_pcr_neg_control == "Neg" ~ 1),
         sample_rerun = str_to_upper(sample_rerun),
         resus_vol = str_replace_all(resus_vol, "\\*", ""))  %>% 
  rename(sample_pass = sample_pass_fail,
         bd_positive = bd_pos_neg,
         bsal_positive = bsal_pos_neg,
         qpcr_neg_control_pass = q_pcr_neg_control,
         edna_comments = notes)

write_csv(collection_serdp_edna, here("clean_tables", "edna_serdp_bd.csv"))

```


# panama edna

## full panama edna data
```{r}
pan_site_edna2022 <- read_csv(here("data", "panama_legacy", "pan_site_edna22.csv")) %>% 
  clean_names() %>% 
  select(fulcrum_id, region, site, start_date)

pan_edna_22 <- read_csv(here("data", "panama_legacy", "pan_edna_22.csv")) %>% 
  clean_names() %>% 
  select(fulcrum_parent_id, geometry, id_edna_sample:notes_of_edna_sample)

full_pan_edna <- left_join(pan_site_edna2022, pan_edna_22, by = (c( "fulcrum_id" = "fulcrum_parent_id")))
```

## panama edna site table
```{r}
  

pan_sites_edna <- full_pan_edna %>% 
  select(region, site, start_date) %>% 
  mutate(region = str_replace_all(str_to_lower(region), " ", "_"),
         site = str_replace_all(str_to_lower(site), " ", "_"),
         start_date = format_iso_8601(parse_date(start_date))) %>% 
  rename(date_collected = start_date)

```

## panama date table
```{r}

pan_date_table <- full_pan_edna %>% 
  select(site, start_date) %>% 
  mutate(site = str_replace_all(str_to_lower(site), " ", "_"),
         start_date = format_iso_8601(parse_date(start_date)),
         year = year(start_date),
         month = month(start_date),
         day = day(start_date))%>% 
  rename(date_collected = start_date)


```


## pan edna metadata
```{r}

pan_edna_metadata <- full_pan_edna %>% 
    mutate(region = str_replace_all(str_to_lower(region), " ", "_"),
         site = str_replace_all(str_to_lower(site), " ", "_"),
         start_date = format_iso_8601(parse_date(start_date))) %>% 
  select(!c(fulcrum_id)) %>% 
  drop_na(geometry) %>% 
  rename(edna_comments = notes_of_edna_sample) %>% 
  mutate(control = if_else(is.na(start_time_negative_control_edna_filtering), 0, 1)) %>% 
  unite(start_time, c(start_time_negative_control_edna_filtering, start_time_sample_edna_filtering), na.rm = T) %>% 
  unite(end_time, c(finish_time_negative_control_edna_filtering, finish_time_sample_edna_filtering), na.rm = T) %>% 
   relocate(control, .after=id_edna_sample)%>% 
  rename(date_collected = start_date) %>% 
  mutate(geometry = str_remove(geometry, "POINT "),
         geometry = str_remove_all(geometry, "[()]"),
         geometry = str_replace(geometry, " ", ","))


write_csv(pan_edna_metadata, here("clean_tables", "edna_panama_survey.csv"))  

```


# bind site tables 
```{r}

edna_sites <- plyr::rbind.fill(pan_sites_edna, serdp_edna_sitetable)

write_csv(edna_sites, here("clean_tables", "edna_site.csv"))

```
# bind date/visit table
```{r}

visit_table <- plyr::rbind.fill(pan_date_table, serdp_edna_visit_table)

write_csv(visit_table, here("clean_tables", "edna_visit.csv"))

```

