---
title: "hobo"
format: html
editor: visual
---

## Load Packages

```{r}

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, here, janitor, lubridate, RPostgres, rstudioapi, DBI, parsedate, stringr, hms,
                 anytime, terra, sp, rgdal, RWmisc, proj4, uuid)

```

## 2022 SN Hobo Data

```{r}

sn_2022_hobo <- read_csv(here("data", "hobo_2022", "SierraNevada_combined.csv")) %>% 
  clean_names()

sun_sn <- sn_2022_hobo %>%
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "sun") %>% 
  select(!location) %>% 
  rename(sun_temperature_c = temperature,
         sun_light_lux = intensity_lux,
         sun_dew_point_c = dew_point,
         sun_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(sun_temperature_c, sun_relative_humidity, sun_dew_point_c, sun_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy")))) %>% 
  select(!c(time_zone))

water_sn <- sn_2022_hobo %>%
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "water") %>% 
  select(!location) %>% 
  rename(water_temperature_c = temperature,
         water_light_lux = intensity_lux,
         water_dew_point_c = dew_point,
         water_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(water_temperature_c, water_relative_humidity, water_dew_point_c, water_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))

full_clean_sn_hobo_2022 <- full_join(sun_sn, water_sn, by = c("site", "date_time")) %>% 
  remove_empty(which = "cols") %>% 
  mutate(region = "california",
         location = "usa",
         time_zone = "GMT-0:700")
  

```

## 2022 Brazil Hobo Data

```{r}

brazil_2022_hobo <- read_csv(here("data", "hobo_2022", "Brazil_combined.csv")) %>% 
  clean_names()

shade_brazil <- brazil_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "shade") %>% 
  select(!location) %>% 
  rename(shade_temperature_c = temperature,
         shade_light_lux = intensity_lux,
         shade_dew_point_c = dew_point,
         shade_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(shade_temperature_c, shade_relative_humidity, shade_dew_point_c, shade_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))
  
soil_brazil <- brazil_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "soil") %>% 
  select(!location) %>% 
  rename(soil_temperature_c = temperature,
         soil_light_lux = intensity_lux,
         soil_dew_point_c = dew_point,
         soil_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(soil_temperature_c, soil_relative_humidity, soil_dew_point_c, soil_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))
  
sun_brazil <- brazil_2022_hobo %>% 
    select(!c(study_area, hobo_name)) %>% 
  filter(location == "sun") %>% 
  select(!location) %>% 
  rename(sun_temperature_c = temperature,
         sun_light_lux = intensity_lux,
         sun_dew_point_c = dew_point,
         sun_relative_humidity = rh) %>% 
    mutate(row = row_number()) %>% 
  pivot_wider(names_from = height, values_from = c(sun_temperature_c, sun_relative_humidity, sun_dew_point_c, sun_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy")))) %>% 
  select(!c(time_zone, row))
  
water_brazil <- brazil_2022_hobo %>%
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "water") %>% 
  select(!location) %>% 
  rename(water_temperature_c = temperature,
         water_light_lux = intensity_lux,
         water_dew_point_c = dew_point,
         water_relative_humidity = rh) %>% 
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = height, values_from = c(water_temperature_c, water_relative_humidity, water_dew_point_c, water_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy")))) %>% 
  select(!c(row, time_zone))

full_clean_brazil_hobo_2022 <- full_join(water_brazil, sun_brazil, by = c("site", "date_time")) %>% 
  full_join(soil_brazil, by = c("site", "date_time")) %>% 
  full_join(shade_brazil, by = c("site", "date_time")) %>% 
  remove_empty(which = "cols") %>% 
  mutate(location = "brazil",
         region = case_when(site %in% c("BO01", "BO02", "BO03") ~ "boraceia",
                            site %in% c("SV04", "SV05") ~ "santa_virginia"),
         site = str_to_lower(site),
         time_zone = "GMT-0:200")
  


```

## 2022 Penn Hobo Data

```{r}

penn_2022_hobo <- read_csv(here("data", "hobo_2022", "PA_combined.csv")) %>% 
  clean_names()

shade_penn <- penn_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "shade") %>% 
  select(!location) %>% 
  rename(shade_temperature_c = temperature,
         shade_light_lux = intensity_lux,
         shade_dew_point_c = dew_point,
         shade_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(shade_temperature_c, shade_relative_humidity, shade_dew_point_c, shade_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))
  
soil_penn <- penn_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "soil") %>% 
  select(!location) %>% 
  rename(soil_temperature_c = temperature,
         soil_light_lux = intensity_lux,
         soil_dew_point_c = dew_point,
         soil_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(soil_temperature_c, soil_relative_humidity, soil_dew_point_c, soil_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))
  
sun_penn <- penn_2022_hobo %>% 
    select(!c(study_area, hobo_name)) %>% 
  filter(location == "sun") %>% 
  select(!location) %>% 
  rename(sun_temperature_c = temperature,
         sun_light_lux = intensity_lux,
         sun_dew_point_c = dew_point,
         sun_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(sun_temperature_c, sun_relative_humidity, sun_dew_point_c, sun_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy")))) %>% 
  select(!c(time_zone))
  
water_penn <- penn_2022_hobo %>%
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "water") %>% 
  select(!location) %>% 
  rename(water_temperature_c = temperature,
         water_light_lux = intensity_lux,
         water_dew_point_c = dew_point,
         water_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(water_temperature_c, water_relative_humidity, water_dew_point_c, water_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))


full_clean_penn_hobo_2022 <- full_join(water_penn, sun_penn, by = c("site", "date_time")) %>% 
  full_join(soil_penn, by = c("site", "date_time")) %>% 
  full_join(shade_penn, by = c("site", "date_time")) %>% 
  remove_empty(which = "cols") %>% 
  mutate(region = "pennsylvania",
         site = case_when(site == "Admin" ~ "admin_pond",
                          site == "Phelps" ~ "phelps_pond",
                          site == "RV" ~ "rv_pond",
                          site == "Tuttle" ~ "tuttle_pond",
                          site == "TW" ~ "tryon_weber",
                          site == "Wood" ~ "wood_lab_pond",
                          site == "Vorisek" ~ "vorisek_pond"),
         location = "usa",
         time_zone = "GMT-04:00")


```

## 2022 Panama Hobo

```{r}

panama_2022_hobo <- read_csv(here("data", "hobo_2022", "Panama_combined.csv")) %>% 
  clean_names()

shade_panama <- panama_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "shade") %>% 
  select(!location) %>% 
  rename(shade_temperature_c = temperature,
         shade_light_lux = intensity_lux,
         shade_dew_point_c = dew_point,
         shade_relative_humidity = rh) %>%
  mutate(row = row_number()) %>% 
  pivot_wider(names_from = height, values_from = c(shade_temperature_c, shade_relative_humidity, shade_dew_point_c, shade_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone, row))
  
soil_panama <- panama_2022_hobo %>% 
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "soil") %>% 
  select(!location) %>% 
  rename(soil_temperature_c = temperature,
         soil_light_lux = intensity_lux,
         soil_dew_point_c = dew_point,
         soil_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(soil_temperature_c, soil_relative_humidity, soil_dew_point_c, soil_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))
  
# sun_panama <- panama_2022_hobo %>% 
#     select(!c(study_area, hobo_name)) %>% 
#   filter(location == "sun") %>% 
#   select(!location) %>% 
#   rename(sun_temperature_c = temperature,
#          sun_light_lux = intensity_lux,
#          sun_dew_point_c = dew_point,
#          sun_relative_humidity = rh) %>% 
#   pivot_wider(names_from = height, values_from = c(sun_temperature_c, sun_relative_humidity, sun_dew_point_c, sun_light_lux)) %>% 
#   mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
#                                                                   "mdy HMS", "mdy")))) %>% 
#   select(!c(time_zone))
  
water_panama <- panama_2022_hobo %>%
  select(!c(study_area, hobo_name)) %>% 
  filter(location == "water") %>% 
  select(!location) %>% 
  rename(water_temperature_c = temperature,
         water_light_lux = intensity_lux,
         water_dew_point_c = dew_point,
         water_relative_humidity = rh) %>% 
  pivot_wider(names_from = height, values_from = c(water_temperature_c, water_relative_humidity, water_dew_point_c, water_light_lux)) %>% 
  mutate(date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))%>% 
  select(!c(time_zone))

full_clean_panama_hobo_2022 <- full_join(water_panama, shade_panama, by = c("site", "date_time")) %>% 
  full_join(soil_panama, by = c("site", "date_time"))  %>% 
  remove_empty(which = "cols") %>% 
  mutate(location = "panama",
         site = case_when(site == "RioBlanco" ~ "rio_blanco",
                          site == "Tigrero" ~ "rio_tigrero",
                          site == "AltosdePiedra" ~ "altos_de_piedra",
                          site == "Campestre" ~ "hotel_campestre"),
         region = case_when(site == "rio_blanco" ~ "el_cope",
                            site == "rio_tigrero" ~ "el_cope",
                            site == "altos_de_piedra" ~ "santa_fe",
                            site == "hotel_campestre" ~ "el_valle"),
         time_zone = "GMT-0:500")
  


```

## 2022 HOBO BFT

```{r}

hobo_bft_2022 <- plyr::rbind.fill(full_clean_brazil_hobo_2022, full_clean_panama_hobo_2022, full_clean_penn_hobo_2022, full_clean_sn_hobo_2022) %>% 
  replace(.=="NULL", NA) %>% 
  remove_empty(which = "cols")

all_hobo_2022 <- hobo_bft_2022 %>% 
  select(!c(region, location))

```

## 2022 sites, regions, and locations

```{r}

sites_2022 <- hobo_bft_2022 %>% 
  select(site, region) %>% 
  group_by(site) %>% 
  unique() 

regions_2022 <- hobo_bft_2022 %>% 
  select(location, region, time_zone) %>% 
  group_by(region) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(!duplicated(temp_id)) %>% 
  select(!temp_id)

locations_2022 <- hobo_bft_2022 %>% 
  select(location) %>% 
  distinct(location)
  

```

# SERDP

## SERDP Hobo location, site, and region

```{r}

serdp_hobo_site <- read_csv(here("clean_tables", "serdp_hobo_site.csv"))

serdp_locs_swap <- serdp_hobo_site %>% 
  select(site, site_code)

# %>% 
#   group_by(site) %>%
#   mutate(hobo_site_id = UUIDgenerate(output = c("uuid")),
#          hobo_region_id = as.UUID(""))

serdp_hobo_region <- read_csv(here("clean_tables", "serdp_hobo_region.csv"))

serdp_hobo_location <- read_csv(here("clean_tables", "serdp_hobo_location.csv"))


```

## read in serdp hobo data

### shade hobo

```{r}

raw_shade_hobo <- read.csv(here("data", "serdp", "hobo", "Shade_HOBO_2021_01_28.csv")) %>% 
  clean_names() 

shade_hobo <- raw_shade_hobo %>% 
  select(!c(x_1, x, location)) %>% 
  rename(serdp_shade_temperature_c = temperature,
         shade_relative_humidity = rh,
         site_code = site,
         #enviro_location = location,
         shade_dew_point_c = dew_point) %>% 
  mutate(site_code = str_to_lower(str_replace_all(site_code, "0", "")),
         date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))),
         shade_dew_point_c = if_else(shade_dew_point_c == "Logged", "", shade_dew_point_c)) 

#write_csv(shade_hobo, here("clean_tables", "shade_hobo.csv"))

rm(raw_shade_hobo)
gc()
```

### soil hobo

```{r}

raw_soil_hobo <- read_csv(here("data", "serdp", "hobo", "Soil_HOBO_2021_01_28.csv")) %>% 
  clean_names()

soil_hobo <- raw_soil_hobo %>% 
  select(!c(x1, x, location)) %>% 
  rename(serdp_soil_temperature_c = temperature,
         site_code = site) %>% 
  mutate(site_code = str_to_lower(str_replace_all(site_code, "0", "")),
         date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))
#write_csv(soil_hobo, here("clean_tables", "soil_hobo.csv"))

rm(raw_soil_hobo)
gc()
```

### sun hobo

```{r}

raw_sun_hobo <- read_csv(here("data", "serdp", "hobo", "Sun_HOBO_2021_01_28.csv")) %>% 
  clean_names()

sun_hobo <- raw_sun_hobo %>% 
  select(!c(x1, x, location)) %>% 
  rename(serdp_sun_temperature_c = temperature,
         site_code = site,
         #enviro_location = location,
         sun_light_lux = light) %>% 
  mutate(site_code = str_to_lower(str_replace_all(site_code, "0", "")),
         date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))))

#write_csv(sun_hobo, here("clean_tables", "sun_hobo.csv"))

rm(raw_sun_hobo)
gc()
```

### water hobo

```{r}
raw_water_hobo <- read_csv(here("data", "serdp", "hobo", "Water_HOBO_2021_01_28.csv")) %>% 
  clean_names()

water_hobo <- raw_water_hobo %>% 
  select(!c(x1, x, location)) %>% 
  rename(serdp_water_temperature_c = temperature,
         site_code = site,
         #enviro_location = location,
         water_light_lux = light) %>% 
  mutate(site_code = str_to_lower(str_replace_all(site_code, "0", "")),
         date_time = format_iso_8601(parse_date_time(date_time, c("mdy H", "mdy HM", 
                                                                  "mdy HMS", "mdy"))),
         water_light_lux = if_else(water_light_lux == "Logged", "", water_light_lux))

#write_csv(water_hobo, here("clean_tables", "water_hobo.csv"))

rm(raw_water_hobo)
gc()
```

## bind hobos

```{r}

all_serdp_hobos <- left_join(shade_hobo, soil_hobo, by = c("site_code", "date_time")) %>% 
  left_join(sun_hobo, by = c("site_code", "date_time")) %>% 
  left_join(water_hobo, by = c("site_code", "date_time")) %>% 
  select(!c(time_zone.y, time_zone.x.x, time_zone.y.y)) %>% 
  rename(time_zone = time_zone.x) %>% 
  left_join(serdp_locs_swap, by = c("site_code")) %>% 
  rename(serdp_sun_light_lux = sun_light_lux,
         serdp_shade_dew_point_c = shade_dew_point_c,
         serdp_water_light_lux = water_light_lux)

# serdp_tz <- all_serdp_hobos %>% 
#   select(site, time_zone) %>% 
#   group_by(site) %>% 
#   unique()

# %>% 
#   mutate(hobo_id = UUIDgenerate(output = c("uuid"), n = n()),
#          hobo_site_id = as.UUID(""))

#write_csv(all_hobos, here("clean_tables", "hobo.csv"))  

```

# combine serdp and 2022

## all locations, regions, sites

```{r}

hobo_location <- locations_2022 %>%
  mutate(hobo_location_id = UUIDgenerate(output = c("uuid"), n = n()))

write_csv(hobo_location, here("clean_tables", "hobo_location.csv"))


hobo_regions <- plyr::rbind.fill(regions_2022, serdp_hobo_region) %>% 
  group_by(region)%>%
  mutate(temp_id = cur_group_id()) %>% 
  filter(!duplicated(temp_id)) %>% 
  select(!temp_id) %>% 
  mutate(hobo_region_id = UUIDgenerate(output = c("uuid")),
         hobo_location_id = as.UUID(""),
         region = str_replace(region, " ", "_"),
         time_zone = if_else(region == "louisiana", "GMT-06:00", time_zone),
         time_zone = if_else(region == "tennessee", "GMT-06:00", time_zone),
         time_zone = if_else(region == "vermont", "GMT-04:00", time_zone),
         time_zone = if_else(region == "new_mexico", "GMT-06:00", time_zone))

write_csv(hobo_regions, here("clean_tables", "hobo_regions.csv"))


hobo_sites <- plyr::rbind.fill(sites_2022, serdp_hobo_site) %>% 
  group_by(site) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(!duplicated(temp_id)) %>% 
  mutate(hobo_site_id = UUIDgenerate(output = c("uuid")),
         hobo_region_id = as.UUID("")) %>% 
  select(!c(utm_zone, utme, utmn, location, temp_id))

write_csv(hobo_sites, here("clean_tables", "hobo_sites.csv"))

```

## all hobo data

```{r}


hobo <- plyr::rbind.fill(all_hobo_2022, all_serdp_hobos) %>%
  mutate(hobo_id = UUIDgenerate(output = c("uuid"), n = n())) %>% 
  #replace(is.null(.), NA) %>% 
  #remove_empty(which = "cols") %>% 
  rename(soil_temperature_c_neg5cm = "soil_temperature_c_-5cm",
         soil_light_lux_neg5cm = "soil_light_lux_-5cm",
         soil_temperature_c_neg10cm = "soil_temperature_c_-10cm") %>% 
  select(!time_zone)

write_csv(hobo, here("clean_tables", "hobo.csv"))

```
