---
title: "qprc_SERDP/SN_build"
author: "Jake Eisaguirre"
date: "2022-10-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, here, janitor, lubridate, RPostgres, parsedate)
```

# Sierra Nevada

## conenct sierra nevada database
```{r}
tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv,
                 dbname = Sys.getenv("sn_dbname"),
                 host = Sys.getenv("sn_host"),
                 port = Sys.getenv("sn_port"),
                 user = Sys.getenv("sn_user"),
                 password = Sys.getenv("sn_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

dbExecute(connection, "set search_path to public")
```

## query sn qpcr data
```{sql, connection=connection, output.var = "sn_bd"}

select * from bd_load


```

## clean sn qpcr data

```{r}

sierra_nevada_bd <- sn_bd %>% 
  rename(bd_swab_id = sample_id)

g <- sierra_nevada_bd %>% 
  group_by(bd_swab_id) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(duplicated(temp_id))

write_csv(sierra_nevada_bd, here("clean_tables", "sierra_nevada_bd.csv"))

```


# SERDP

## load serdp qpcr data
```{r}

qpcr_2017 <- read_csv(here("qpcr_data", "SERDP qPCR results 2017_220721.csv")) %>% 
  clean_names()

qpcr_2018 <- read_csv(here("qpcr_data", "SERDP qPCR results 2018_191129.csv")) %>% 
  clean_names()

qpcr_2019 <- read_csv(here("qpcr_data", "SERDP qPCR results 2019_220721.csv")) %>% 
  clean_names()

serdp_bd <- plyr::rbind.fill(qpcr_2017, qpcr_2018, qpcr_2019) %>% 
  rename(bd_load = sample_bd_swab_qty) %>% 
  select(sample_id, qpcr_date, c(qpcr_neg_cont:bd_load), notes) %>% 
  rename(bd_swab_id = sample_id) %>% 
  drop_na(bd_swab_id) %>% 
  mutate(qpcr_date = parse_date(qpcr_date),
         sample_ipc = str_to_lower(sample_ipc),
         sample_rerun = str_to_lower(sample_rerun)) %>% 
  filter(!bd_swab_id %in% c("NEG EXTRACT CONTROL", "POS EXTRACT CONTROL", 
                            "191020-16-PA05-LICL", "170709-NM-NM")) # <- temp remove last ID until we know what to do with it

write_csv(serdp_bd, here("clean_tables", "serdp_bd.csv"))

# pure dubs "191020-16-PA05-LICL" and "170709-NM-NM"
dups <- serdp_bd %>% 
  group_by(bd_swab_id) %>% 
  mutate(temp_id = cur_group_id()) %>% 
  filter(duplicated(temp_id))

# missing ~141 IDs in capture table to align with qpcr table
# test <- serdp_capture %>% 
#   filter(!is.na(sample_id),
#          sample_id %in% serdp_bd$bd_swab_id)
# 
# t <- anti_join(serdp_bd, test,  by = c("bd_swab_id" = "sample_id"))



```

# Panama

## load panama qpcr data
```{r}

panama_qpcr <- read_csv(here("data", "panama_legacy", "clean_tables", "clean_pan_cap.csv")) %>% 
  clean_names() %>% 
  select(bd_swab_id, pcr) %>% 
  drop_na(pcr) %>% 
  rename(bd_load = pcr) %>% 
  filter(!bd_swab_id == "150608_01") # temp remove "150608_01" until we know what to do with it

write_csv(panama_qpcr, here("clean_tables", "panama_bd_temp.csv"))

#dub id "150608_01"
l <- panama_qpcr %>% 
  filter(duplicated(bd_swab_id))
```

# Brazil
## load legacy brazil qpcr data
```{r}

brazil_legacy_qpcr <- read_csv(here("data", "brazil_legacy", "bd.csv")) %>% 
  drop_na() %>% 
  rename(bd_swab_id = swab_id)

write_csv(brazil_legacy_qpcr, here("clean_tables", "brazil_legacy_bd"))

```


# temp qpcr data
```{r}

# tryCatch({
#     drv <- dbDriver("Postgres")
#     print("Connecting to Database…")
#     connection <- dbConnect(drv,
#                  dbname = Sys.getenv("aws_dbname"),
#                  host = Sys.getenv("aws_host"),
#                  port = Sys.getenv("aws_port"),
#                  user = Sys.getenv("aws_user"),
#                  password = Sys.getenv("aws_password"),
#                  timezone=NULL)
#     print("Database Connected!")
#     },
#     error=function(cond) {
#             print("Unable to connect to Database.")
#     })
# 
# dbExecute(connection, "set search_path to 'survey_data'")

temp_shiny_bd <- plyr::rbind.fill(panama_qpcr, serdp_bd, sierra_nevada_bd) %>% 
  select(bd_swab_id, bd_load)

write_csv(temp_shiny_bd, here("clean_tables", "temp_shiny_bd.csv"))


#dbWriteTable(connection, "temp_shiny_bd", temp_shiny_bd)

```

