---
title: "database_push"
author: "Jake Eisaguirre"
date: "2022-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, DBI, RPostgres, here)
```

# Clean tables

## read in all `clean_tables` .csv files
```{r}

# slow method for reading csv files

filenames <- gsub("\\.csv$","", list.files(here("clean_tables")))

for(i in filenames){
  assign(i, read.csv(here("clean_tables", paste(i, ".csv", sep=""))))
}
```


# Database

## connect to `RIBBiTR` database
```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("dbname"),
                 host = Sys.getenv("host"), 
                 port = Sys.getenv("port"),
                 user = Sys.getenv("user"), 
                 password = Sys.getenv("password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })


```

## upload unique tables to `RIBBiTR` DB - `survey_data` schema
```{r}
# remove current schema
dbExecute(connection, "DROP SCHEMA survey_data CASCADE")

# create new empty schema
dbExecute(connection, "create schema survey_data")

# set schema path
dbExecute(connection, "set search_path to survey_data")

#location table load
dbWriteTable(connection, 'location', location, overwrite=T,
             field.types = c(location = "varchar(6)"))

#region table load
dbWriteTable(connection, 'region', regions, overwrite=T,
             field.types = c(region = "varchar(16)",
                             location = "varchar(6)"))

#site table load
dbWriteTable(connection, 'site', sites, overwrite=T,
             field.types = c(site = "varchar(40)",
                             region = "varchar(16)", 
                             location = "varchar(6)",
                             utm_zone = "int",
                             utme = "int",
                             utmn = "int",
                             site_code = "varchar(4)",
                             site_comments = "varchar",
                             elevation_m = "int",
                             area_sqr_m = "int",
                             depth_m = "float8",
                             topo = "varchar(20)",
                             wilderness = "varchar(12)"))

#visit table load
dbWriteTable(connection, 'visit', visit, overwrite=T,
             field.types = c(campaign = "int",
                             date = "date",
                             site = "varchar(40)",
                             survey_time = "varchar(5)",
                             visit_comments = "varchar",
                             site_code = "varchar(4)",
                             visit_status = "varchar(8)"))

#brazil_legacy_survey table load
dbWriteTable(connection, 'brazil_legacy_survey', brazil_legacy_survey, overwrite=T,
             field.types = c(start_time = "time",
                             end_time = "time",
                             site = "varchar(40)",
                             date = "date",
                             survey_time = "varchar(5)",
                             campaign = "int",
                             detection_type = "varchar(7)",
                             duration_minutes = "int"))

#panama_survey table load
dbWriteTable(connection, 'panama_survey', panama_survey, overwrite=T,
             field.types = c(site = "varchar(40)",
                             transect = "varchar(15)",
                             date = "date",
                             survey_time = "varchar(5)",
                             frog_presence = "boolean",
                             observers = "varchar",
                             number_observers = "int",
                             start_time = "time",
                             end_time = "time",
                             duration_minutes = "int",
                             samp_loc = "varchar",
                             pressure_hg = "float8",
                             humidity_percent = "float8",
                             wind_speed_m_s = "float8",
                             air_temp_c = "float8",
                             water_temp_c = "float8",
                             dissolved_o2_percent = "float8",
                             p_h = "float8",
                             conductivity_uS_cm = "float8",
                             tds_ppm = "float8",
                             salinity_ppt = "float8",
                             cloud_cover_percent = "varchar",
                             precip = "varchar",
                             survey_comments = "varchar",
                             qaqc_survey = "varchar",
                             detection_type = "varchar(7)",
                             soil_humidity_m3m3 = "float8"))

#penn_survey table load
dbWriteTable(connection, 'penn_survey', penn_survey, overwrite=T,
             field.types = c(site = "varchar(13)",
                             date = "date",
                             observer = "varchar",
                             detection_type = "varchar(7)",
                             start_time = "time",
                             end_time = "time",
                             duration_minutes = "int",
                             survey_time = "varchar(5)"))

#serdp_survey table load
dbWriteTable(connection, 'serdp_survey', serdp_survey, overwrite=T,
             field.types = c(date = "date",
                             site_code = "varchar(4)",
                             survey_time = "varchar(5)",
                             no_of_investigators = "varchar",
                             investigator_i_ds = "varchar",
                             start_time = "time",
                             end_time = "time",
                             wind_speed_scale = "int",
                             precipitation_during_visit = "varchar",
                             precipitation_last_48_h = "varchar",
                             temperature_last_48_h = "varchar",
                             percent_cloud_cover = "int",
                             weather_condition_notes = "varchar",
                             pressure_psi = "float8",
                             pressure_psi_drop = "float8",
                             relative_humidity = "float8",
                             relative_humidity_drop = "float8",
                             wind_speed_mpers_min = "float8",
                             wind_speed_mpers_max = "float8",
                             air_temp_deg_c = "float8",
                             air_temp_deg_c_drop = "float8",
                             water_temp_deg_c = "float8",
                             p_h = "float8",
                             conductivity_uS_cm = "float8",
                             tds_ppm = "float8",
                             densiometer_d1_num_covered = "boolean",
                             d1_n = "int",
                             d1_s = "int",
                             d1_e = "int",
                             d1_w = "int",
                             d1_percent_cover = "float8",
                             densiometer_d2_num_covered = "boolean",
                             d2_n = "int",
                             d2_s = "int",
                             d2_e = "int",
                             d2_w = "int",
                             d2_percent_cover = "float8",
                             depth_of_water_from_d2_cm = "float8",
                             percent_vegetation_cover = "int",
                             vegetation_notes = "varchar",
                             e_dna_sample = "boolean",
                             survey_comments = "varchar",
                             pressure_hg = "float8",
                             wind_speed_mpers = "float8",
                             secchi_depth_cm = "int",
                             site = "varchar",
                             detection_type = "varchar(7)",
                             duration_minutes = "int"))

#sn_survey table load
dbWriteTable(connection, 'sierra_nevada_survey', sn_survey_table, overwrite=T,
             field.types = c(site = "varchar(5)",
                             date = "date",
                             detection_type = "varchar(7)",
                             wind = "varchar(6)",
                             sky = "varchar(8)",
                             start_time = "time",
                             end_time = "time",
                             duration = "int",
                             air_temp = "int",
                             water_temp = "int",
                             water_time = "time",
                             fish = "boolean",
                             description = "varchar",
                             survey_comments = "varchar",
                             survey_quality = "varchar(4)",
                             survey_time = "varchar(5)"))

# ves table load - NEED to remove "many" from count in VES data
dbWriteTable(connection, 'ves', ves, overwrite=T,
             field.types = c(site = "varchar(18)",
                             date = "date",
                             survey_time = "varchar(5)",
                             species_ves = "varchar",
                             detection_type = "varchar(7)",
                             count = "int",
                             detection_location = "varchar",
                             microhab = "varchar",
                             life_stage = "varchar",
                             sex = "varchar(7)",
                             ves_comments = "varchar",
                             microhab_moredetail ="varchar",
                             visual_animal_state = "varchar(5)"))

# aural table load - NEED to remove "many" from count in Aural data
dbWriteTable(connection, 'aural', aural, overwrite=T,
             field.types = c(date = "date",
                             site = "varchar(18)",
                             species_aural = "varchar",
                             call_index = "varchar",
                             aural_comments = "varchar",
                             detection_type = "varchar(7)",
                             survey_time = "varchar(5)",
                             count = "int",
                             detection_location = "varchar",
                             microhab = "varchar",
                             life_stage = "varchar",
                             sex = "varchar(7)",
                             microhab_moredetail = "varchar"))

# capture table load
dbWriteTable(connection, 'capture', capture, overwrite=T,
             field.types = c(site = "varchar(35)",
                             date = "date",
                             survey_time = "varchar(5)",
                             species_capture = "varchar",
                             detection_type = "varchar(7)",
                             time_of_capture = "time",
                             capture_trx_loc = "varchar",
                             microhabitat_type = "varchar",
                             body_temp_c = "float8",
                             substrate_temp_c = "float8",
                             svl_mm = "float8",
                             body_mass_g = "float8",
                             life_stage = "varchar",
                             sex = "varchar",
                             capture_animal_state = "varchar(7)",
                             bd_swab_id = "varchar",
                             genetic_id = "varchar",
                             bacterial_swab_id = "varchar",
                             amp_id = "varchar",
                             e_dna = "varchar",
                             photo = "boolean",
                             photo_id = "varchar",
                             capture_comments = "varchar",
                             microhab_moredetail = "varchar",
                             body_and_bag_mass_g = "float8",
                             bag_mass_g = "float8",
                             mucosome_id = "varchar",
                             microbiome_swab_id = "varchar",
                             ampshcl = "varchar",
                             campaign = "int",
                             marked = "boolean",
                             capture_utme = "float8",
                             capture_utmn = "float8",
                             bag_id = "varchar",
                             processor = "varchar",
                             capture_type = "varchar(9)",
                             capture_mark_recapture = "varchar",
                             crispr_id = "varchar",
                             amp_id_2 = "varchar",
                             amp_id_3 = "varchar",
                             amp_id_4 = "varchar",
                             antibody_id = "varchar",
                             antibody_id_2 = "varchar",
                             antibody_id_3 = "varchar",
                             antibody_id_4 = "varchar",
                             site_code = "varchar(4)",
                             microhabitat_notes = "varchar",
                             tail_length_mm = "float8",
                             buckets = "varchar",
                             location = "varchar",
                             temp_gun = "varchar",
                             clearcut = "varchar",
                             number_of_mites = "varchar",
                             flir = "varchar",
                             tad_stage = "int"))

# serdp bd genomic data
dbWriteTable(connection, 'serdp_bd_genomic', serdp_bd_genom, overwrite=T,
             field.types = c(genetic_id = "varchar(20)",
                             seq_run = "int",
                             n_seqs_187 = "int",
                             avg_alleles_per_locus = "float8",
                             lineage_astral_187 = "varchar",
                             lineage_dapc_2_99cut = "varchar"))

# serdp newt microbiome mucosome antifungal
dbWriteTable(connection, 'serdp_newt_microbiome_mucosome_antifungal', serdp_newt_microbiome_mucosome_antifungal, 
             overwrite=T,
             field.types = c(swab_id = "varchar",
                             observed_features = "int",
                             faith_pd = "float8",
                             shannon_entropy = "float8",
                             pielou_evenness = "float8",
                             exp_shannon = "float8",
                             all_seqs_richness = "int",
                             total_all_seqs = "int",
                             propor_total_all_seqs = "float8",
                             propor_total_all_seqs_richness = "float8",
                             facilitating_richness = "int",
                             total_facilitating = "int",
                             propor_total_facilitating = "float8",
                             propor_total_facilitating_richness = "float8",
                             anti_fungal_richness = "int",
                             total_anti_fungal = "int",
                             propor_total_anti_fungal = "float8",
                             propor_total_anti_fungal_richness = "float8",
                             ttx_richness = "int",
                             total_ttx = "int",
                             propor_total_ttx = "float8",
                             corrected_viability = "float8",
                             extraction_kit = "varchar",
                             shedding_ct = "float8",
                             shedding_bd_mean = "float8",
                             shedding_bd_swab = "float8",
                             shedding_infected = "varchar",
                             mucosome_id = "varchar",
                             microbiome_swab_id = "varchar"))

# serdp amp 
dbWriteTable(connection, 'serdp_amp', serdp_amp, overwrite=T,
             field.types = c(amp_id = "varchar",
                             temp_1p_1368_9 = "boolean",
                             temp_1p_intensity = "float8",
                             brev_1pi_1834 = "boolean",
                             brev_1pi_intensity = "float8",
                             brev_1pa_2562_4 = "boolean",
                             brev_1pa_intensity = "float8",
                             brev_1pb_2576_4 = "boolean",
                             brev_1pb_intensity = "float8",
                             brev_1pg_2595_5_brev_1pk_2593_5 = "boolean",
                             brev_1pg_k_intensity = "float8",
                             rana_2p_2999_5 = "boolean",
                             rana_2p_intensity = "float8",
                             rana_2pb_3521 = "boolean",
                             rana_2pb_intensity = "float8",
                             maldi_notes = "varchar",
                             censor = "boolean",
                             total_peptides_ug = "float8",
                             water = "boolean",
                             season = "varchar",
                             julian_date = "int",
                             peptides_ug_gbw = "float8",
                             peptides_ug_cm2 = "float8",
                             peptides_ug_ml_mucus = "float8",
                             smi = "float8",
                             gia_plate_pos_growth = "float8",
                             date_gia = "date",
                             gia_final_reading = "int",
                             percent_inhibition_16_ug_ml = "float8",
                             percent_inhibition_31_ug_ml = "float8",
                             percent_inhibition_63_ug_ml = "float8",
                             percent_inhibition_125_ug_ml = "float8",
                             percent_inhibition_250_ug_ml = "float8",
                             percent_inhibition_500_ug_ml = "float8",
                             slope = "float8",
                             ic50 = "float8",
                             mic = "int",
                             gia_notes = "varchar",
                             daily_avg_t = "float8",
                             daily_max_t = "float8",
                             daily_min_t = "float8",
                             dailyrange_t = "float8",
                             daily_rh = "float8",
                             daily_r_hrange = "float8",
                             diff_temp = "float8",
                             last2humidity = "float8",
                             last2t_air = "float8",
                             last2t_maxair = "float8",
                             lastmo_air = "float8",
                             delta_air2w = "float8",
                             delta_air1m = "float8",
                             degreedays = "int"))

# serdp bd_load
dbWriteTable(connection, 'serdp_bd', serdp_bd, overwrite=T,
             field.types = c(bd_swab_id = "varchar",
                             qpcr_date = "date",
                             qpcr_neg_cont = "varchar",
                             sample_quality = "varchar",
                             sample_ipc = "varchar",
                             sample_rerun = "varchar",
                             sample_bd = "varchar",
                             sample_bd_ct = "float8",
                             sample_bd_qty = "float8",
                             bd_load = "float8",
                             notes = "varchar"))

# sierra bd_load
dbWriteTable(connection, 'sierra_nevada_bd', sierra_nevada_bd, overwrite=T,
             field.types = c(bd_swab_id = "varchar",
                             replicate = "int",
                             start_quant = "float8",
                             std_type = "varchar",
                             dilution = "int",
                             bd_load = "float8"))

#panama temp bd_load
dbWriteTable(connection, 'panama_bd_temp', panama_bd_temp, overwrite=T,
             field.types = c(bd_swab_id = "varchar",
                             bd_load = "float8"))




```

## upload data to `hobo` schema
```{r}
dbExecute(connection, "set search_path to hobo")

# hobo table loads
## hobo site
dbWriteTable(connection, 'hobo_site', hobo_site, overwrite=T,
             field.types = c(site_code = "varchar(4)",
                             region = "varchar(12)",
                             site = "varchar",
                             site_comments = "varchar",
                             location = "varchar(6)",
                             utm_zone = "int",
                             utme = "float8",
                             utmn = "float8"))
## hobo shade
dbWriteTable(connection, 'shade_hobo', shade_hobo, overwrite=T,
             field.types = c(date_time = "timestamp",
                             shade_temperature_c = "float8",
                             relative_humidity = "float8",
                             dew_point_c = "float8",
                             site_code = "varchar(4)",
                             enviro_location = "varchar(5)",
                             time_zone = "varchar"))
## hobo soil
dbWriteTable(connection, 'soil_hobo', soil_hobo, overwrite=T,
             field.types = c(date_time = "timestamp",
                             soil_temperature_c = "float8",
                             site_code = "varchar(4)",
                             enviro_location = "varchar(4)",
                             time_zone = "varchar"))
## hobo sun
dbWriteTable(connection, 'sun_hobo', sun_hobo, overwrite=T,
             field.types = c(date_time = "timestamp",
                             sun_temperature_c = "float8",
                             light = "float8",
                             site_code = "varchar(4)",
                             enviro_location = "varchar(3)",
                             time_zone = "varchar"))
## hobo water
dbWriteTable(connection, 'water_hobo', water_hobo, overwrite=T,
             field.types = c(date_time = "timestamp",
                             water_temperature_c = "float8",
                             light = "float8",
                             site_code = "varchar(4)",
                             enviro_location = "varchar(12)",
                             time_zone = "varchar"))
```

## upload data to `antifungal_isolate` schmea
```{r}
dbExecute(connection, "set search_path to antifungal_isolate")

dbWriteTable(connection, 'antifungal_isolate_ref', antifungal_isolate_ref, overwrite=T)


```

## upload data to `e_dna` schema
```{r}
# set search path
dbExecute(connection, "set search_path to e_dna")

#location table load
dbWriteTable(connection, 'edna_location', location, overwrite=T,
             field.types = c(location = "varchar(6)"))

#region table load
dbWriteTable(connection, 'edna_region', regions, overwrite=T,
             field.types = c(region = "varchar(16)",
                             location = "varchar(6)"))

#site table load
dbWriteTable(connection, 'edna_site', edna_site, overwrite=T,
             field.types = c(region = "varchar(16)",
                             site = "varchar",
                             date_collected = "date",
                             site_code = "varchar(4)"))

#edna visit load
dbWriteTable(connection, 'edna_visit', edna_visit, overwrite=T,
             field.types = c(site = "varchar",
                             date_collected = "date",
                             year = "int",
                             month = "int",
                             day = "int",
                             site_code = "varchar(4)"))
#edna serdp processed
dbWriteTable(connection, 'edna_serdp_bd', edna_serdp_bd, overwrite=T,
             field.types = c(pool_id = "varchar",
                             pool_id_regardless_of_half = "varchar",
                             h1_or_h2 = "varchar",
                             sample_pass = "boolean",
                             site_code = "varchar",
                             date_collected = "date",
                             number_filters = "int",
                             control = "boolean",
                             num_replicates = "int",
                             resus_vol = "int",
                             ext_date = "date",
                             ext_method = "varchar",
                             ext_tech = "varchar",
                             ext_location = "varchar",
                             date_ran = "date",
                             q_pcr_lab = "varchar",
                             q_pcr_tech = "varchar",
                             bd_positive = "boolean",
                             qpcr_well_pos = "varchar",
                             bd_pos_neg_per_replicate = "varchar",
                             ct_mean = "varchar",
                             quantity_mean_rep1 = "float8",
                             quantity_mean_rep2 = "float8",
                             quantity_mean_rep3 = "float8",
                             quantity_mean_ave = "float8",
                             bd_per_liter = "float8",
                             bsal_positive = "boolean",
                             ipc = "varchar",
                             dilution_multiplier = "varchar",
                             qpcr_neg_control_pass = "boolean",
                             sample_rerun = "boolean",
                             q_pcr_results_file = "varchar",
                             edna_comments = "varchar",
                             region = "varchar"))

#edna pan metadata
dbWriteTable(connection, 'edna_panama_survey', edna_panama_survey, overwrite=T,
             field.types = c(region = "varchar",
                             site = "varchar",
                             date_collected = "date",
                             geometry = "point",
                             control = "boolean",
                             transect_meters_sampled_m = "int",
                             start_time = "time",
                             end_time = "time",
                             volume_of_filtered_sample_ml = "int",
                             edna_comments = "varchar"))





```

