---
title: "hobo_push"
author: "Jake Eisaguirre"
date: "2022-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages
librarian::shelf(tidyverse, DBI, RPostgres, here, uuid)
```

# Clean tables

## read in all `clean_tables` .csv files
```{r, echo=F, message=F}

# clear environment
rm(list=ls())

# slow method for reading csv files

filenames <- gsub("\\.csv$","", list.files(here("clean_tables")))

for(i in filenames){
  assign(i, read_csv(here("clean_tables", paste(i, ".csv", sep=""))))
}
```


# Database

## connect to `RIBBiTR` database
```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"), 
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_user"), 
                 password = Sys.getenv("aws_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

```

## upload data to `hobo` schema
```{r}
# remove current schema
dbExecute(connection, "DROP SCHEMA hobo CASCADE")

# create new empty schema
dbExecute(connection, "create schema hobo")

# set schema path
dbExecute(connection, "set search_path to hobo")

# hobo table loads

## hobo location
dbWriteTable(connection, 'hobo_location', hobo_location, overwrite=T,
             field.types = c(location = "varchar",
                             hobo_location_id = "uuid"))

## hobo region
dbWriteTable(connection, 'hobo_region', hobo_regions, overwrite=T,
             field.types = c(region = "varchar",
                             time_zone = "varchar",
                             location = "varchar",
                             hobo_region_id = "uuid",
                             hobo_location_id = "uuid"))

## hobo site
dbWriteTable(connection, 'hobo_site', hobo_sites, overwrite=T,
             field.types = c(site_code = "varchar(4)",
                             region = "varchar",
                             site = "varchar",
                             site_comments = "varchar",
                             hobo_site_id = "uuid",
                             hobo_region_id = "uuid"))


# hobo <- hobo %>% 
#   mutate(hobo_site_id = as.UUID(hobo_site_id)) %>% 
#   spec_table()

## all hobo
dbWriteTable(connection, 'hobo', hobo, overwrite=T,
             field.types = c(date_time = "timestamp"))
# ,
#                              serdp_shade_temperature_c = "float8",
#                              serdp_shade_relative_humidity = "float8",
#                              serdp_shade_dew_point_c = "float8",
#                              site_code = "varchar",
#                              serdp_soil_temperature_c = "float8",
#                              serdp_sun_temperature_c = "float8",
#                              serdp_sun_light_lux = "float8",
#                              serdp_water_temperature_c = "float8",
#                              serdp_water_light_lux = "float8",
#                              hobo_id = "uuid",
#                              site = "varchar",
#                              water_temperature_c_5cm = "float8",
#                              water_light_lux_5cm = "float8",
#                              sun_temperature_c_0cm= "float8",
#                              sun_temperature_c_50cm= "float8",
#                              sun_relative_humidity_50cm= "float8",
#                              sun_dew_point_c_50cm= "float8",
#                              sun_light_lux_0cm= "float8",
#                              soil_temperature_c_neg5cm= "float8",
#                              soil_light_lux_neg5cm= "float8",
#                              shade_temperature_c_0cm= "float8",
#                              shade_temperature_c_50cm= "float8",
#                              shade_light_lux_0cm= "float8",
#                              shade_light_lux_50cm= "float8",
#                              shade_temperature_c_5cm= "float8",
#                              shade_temperature_c_100cm= "float8",
#                              shade_relative_humidity_100cm= "float8",
#                              shade_dew_point_c_100cm= "float8",
#                              shade_light_lux_5cm= "float8",
#                              water_temperature_c_20cm= "float8",
#                              water_temperature_c_35cm= "float8",
#                              sun_temperature_c_25cm= "float8",
#                              sun_light_lux_25cm= "float8",
#                              soil_temperature_c_neg10cm= "float8",
#                              shade_temperature_c_25cm= "float8",
#                              shade_relative_humidity_50cm= "float8",
#                              shade_dew_point_c_50cm= "float8",
#                              shade_light_lux_25cm= "float8",
#                              water_light_lux_35cm= "float8"
#                              ))


## hobo shade
# dbWriteTable(connection, 'shade_hobo', shade_hobo, overwrite=T,
#              field.types = c(date_time = "timestamp",
#                              shade_temperature_c = "float8",
#                              relative_humidity = "float8",
#                              dew_point_c = "float8",
#                              site_code = "varchar(4)",
#                              enviro_location = "varchar(5)",
#                              time_zone = "varchar"))
# ## hobo soil
# dbWriteTable(connection, 'soil_hobo', soil_hobo, overwrite=T,
#              field.types = c(date_time = "timestamp",
#                              soil_temperature_c = "float8",
#                              site_code = "varchar(4)",
#                              enviro_location = "varchar(4)",
#                              time_zone = "varchar"))
# ## hobo sun
# dbWriteTable(connection, 'sun_hobo', sun_hobo, overwrite=T,
#              field.types = c(date_time = "timestamp",
#                              sun_temperature_c = "float8",
#                              light = "float8",
#                              site_code = "varchar(4)",
#                              enviro_location = "varchar(3)",
#                              time_zone = "varchar"))
# ## hobo water
# dbWriteTable(connection, 'water_hobo', water_hobo, overwrite=T,
#              field.types = c(date_time = "timestamp",
#                              water_temperature_c = "float8",
#                              light = "float8",
#                              site_code = "varchar(4)",
#                              enviro_location = "varchar(12)",
#                              time_zone = "varchar"))
```